config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  
  root to: "welcome#index"
  resources :users, only: [:index, :show, :new] do
    resources :categories, only: [:new, :create, :show, :index, :destroy]
    resources :payments, only: [:new, :create, :index, :show, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Category, author_id: user.id
    can :manage, Payment, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :payment_categories, dependent: :destroy
  has_many :payments, through: :payment_categories, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :payment_categories, dependent: :destroy
  has_many :categories, through: :payment_categories, dependent: :destroy

  # Valudation
  validates :name, presence: true, length: { minimum: 2 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/payment_category.rb
class PaymentCategory < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :name, presence: true, length: { in: 2..40 }

  # Associations
  has_many :payments, dependent: :destroy
  has_many :categories, class_name: 'Category', foreign_key: 'author_id', dependent: :destroy
  has_many :payment_categories, through: :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Set up user authentication
  before_action :authenticate_user!, unless: :welcome_index_url
  # Add addtional parameters
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Customize redirect hooks
  def after_sign_in_path_for(_resource)
    user_categories_url(current_user)
  end
  # Permit addtional parameters (@lazy)

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[name email password confirm_password]
    )
    devise_parameter_sanitizer.permit(
      :sign_in, keys: %i[email password]
    )
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @author = current_user
    @categories = Category.all
    @category_sums = {}
    @categories.each do |category|
      @category_sums[category.id] = category.payments.sum(:amount)
    end
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @author = current_user
    @category = @author.categories.build(author_id: current_user.id, **category_params)
    if @category.save
      flash[:success] = 'Successfully added your category!.'
      redirect_to user_categories_path(@author)
    else
      flash[:error] = 'There was an error while creating the category.'
      render :new
    end
  end

  def destroy; end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payment_categories_controller.rb
class PaymentCategoriesController < ApplicationController
  def index; end

  def show; end

  def new; end

  def create; end

  def destroy; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
    @categories = Category.all
  end

  def show
    @category_id = params[:id]
    @category = Category.find(@category_id)
    @category_name = @category.name
    payment_categories = PaymentCategory.where(category_id: @category_id)
    @payments = Payment.where(id: payment_categories.pluck(:payment_id)).order(created_at: :desc)
    @sum = @payments.sum(:amount)
  end

  def new
    @payment = Payment.new
    @categories = Category.all
  end

  def create
    @payment = Payment.new(author_id: current_user.id, **payment_params)
    category_ids = params[:payment][:category_ids].reject(&:empty?)

    if @payment.save
      category_ids.each do |category_id|
        PaymentCategory.create(payment: @payment, category_id:)
      end
      my_category = category_ids.first
      flash[:success] = 'Successfully captured payment.'
      redirect_to user_payment_url(author_id: current_user.id, id: my_category)
    else
      flash[:error] = 'There was an error while capturing the payment.'
      render :new
    end
  end

  def destroy
    return unless @payment.destroy

    redirect_to user_payments_url
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end

  def new; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payment_categories_helper.rb
module PaymentCategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/create.html.erb
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<header class="header-cat">
<nav class="category-nav">
<i class="fas fa-bars"></i>
<h1>Categories</h1>
<i class="fas fa-search"></i>
</nav>
</header>
<section class="category-container">
<% if @categories.empty? %>
<p>Please add categories to see here, currently there are no categories for the budget</p>
<% else %>
<% @categories.each do |category| %>
    <article class="category-article">
    <%= link_to user_payment_path(current_user.id, category.id) do %>
      <div class="article-inner">
    <div class="icon"><%=image_tag(category.icon, :alt => "category icon.", :class => "category-icon") %></div>
    <div class="name-category"><%= category.name %></div>
    <div class="total-category"><span class="total-span">$<%= @category_sums[category.id] %></span></div>
    </div>
    <% end %>
</article>
<% end %>
    <% end %>
    <div class="add-category-btn">
    <%= link_to "Add new Category", new_user_category_path, class: "add-category" %>
  </div>
</section>

app/views/categories/new.html.erb
<header class="header-cat">
<nav class="category-nav">
<%= link_to user_categories_path(current_user) do %>
  <i class="fas fa-less-than"></i>
  <% end %>
<h1>New Category</h1>
<i class="fas fa-search"></i>
</nav>
</header>
<div class="category-container-new">
<%= form_with(model: @category, url: user_categories_path) do |form| %>
    <div class="form-food">
   
  <div class="label-category">
    <%= form.text_field :name, class: "name-1", placeholder: "Name" %>
    <%= form.text_field :icon, class: "icon-field", placeholder: "Icon"  %>
  </div>
  <div class="category-submit-btn">
    <p><%= form.submit "Save", class: "new-category-btn" %></p>
  </div>
  </div>
<% end %>
<div>

app/views/categories/show.html.erb
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expenzy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700&display=swap">
  </head>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/payment_categories/create.html.erb
<p>Find me in app/views/payment_categories/create.html.erb</p>

app/views/payment_categories/destroy.html.erb
<p>Find me in app/views/payment_categories/destroy.html.erb</p>

app/views/payment_categories/index.html.erb
<p>Find me in app/views/payment_categories/index.html.erb</p>

app/views/payment_categories/new.html.erb
<p>Find me in app/views/payment_categories/new.html.erb</p>

app/views/payment_categories/show.html.erb
<p>Find me in app/views/payment_categories/show.html.erb</p>

app/views/payments/create.html.erb
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/destroy.html.erb
<p>Find me in app/views/payments/destroy.html.erb</p>

app/views/payments/index.html.erb
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<header class="header-cat">
<nav class="category-nav payment-nav">
<%= link_to user_categories_path(current_user) do %>
  <i class="fas fa-less-than"></i>
  <% end %>
<h1>Add new payment</h1>
<i class="fas fa-search"></i>
</nav>
</header>
<div class="new-payment-container">
<%= form_for @payment, url: user_payments_path, method: :post do |f| %>
    <div class="label-payment">
      <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
    <%= f.number_field :amount, class: "form-control", placeholder: "Amount", required: true %>
  </div>
  <div class="categories-form-cont">
  <%= f.label :category_ids, "Categories", class: "all-categories-label" %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <div class="form-check">
      <%= cb.check_box(class: "form-check-input") %>
      <%= cb.label(class: "form-check-label") %>
    </div>
  <% end %>
</div>
    <div class="payment-submit-btn">
      <%= f.submit "Save", class: "new-payment-btn" %>
    </div>
  <% end %>
  </div>
  

app/views/payments/show.html.erb
<header class="header-payment">
<nav class="nav-payment">
<%= link_to user_categories_path(current_user) do %>
<i class="fas fa-less-than"></i>
<% end %>
<h1>Payments</h1>
<i class="fas fa-search"></i>
</nav>
<div class="recent-content">
<p class="p1">Most recent <span>.</span></p>
<p class="p2">Most Ancient <span>&nbsp;</span></p>
</div>
</header>
<section class="payments-section">
<div class="top">
<p><%= @category_name %></p>
<h3>$<%= @sum %></h3>
</div>
<% if @payments.empty? %>
<p>There are no payments for this category</p>
<% else %>
<% @payments.each do |payment| %>
    <article class="payment-article">
    <div class="payment-div">
    <%=image_tag(@category.icon, :alt => "category icon.", :class => "category-payment-icon") %>
<p class="pay-name"><%= payment.name %></p>
<h4>$<%= payment.amount %></h4>
</div>
<div class="date-div">
<p class="pay-date"><%= payment.created_at.strftime('%Y-%m-%d') %></p>
</div>
    </article>
    <% end %>
    <% end %>
    <div class="add-transaction">
    <%= button_to "Add a payment" , new_user_payment_path, method: :get, class: "add-payment" %>
    </div>
</section>

app/views/users/index.html.erb
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.erb
<section class="landing-page">
 <div class="landing-cont">
  <h1>Expenzy</h1>
    <div class="links-btns">     
       <button class="sign-in-button"><%= link_to "LOGIN", new_user_session_path %></button>
       <button class="sign-up-button"><%= link_to "SIGN UP", new_user_registration_path %></button>
    </div>
 </div
</section>